// Shared private-key loading for CLI commands that need to sign/decrypt as a
// specific identity (`audit`, `my-salary`). Deliberately flexible about the
// file shape so `deployments/*.json` — which already holds every testnet key
// generated by scripts/deploy-sepolia.ts — can be pointed at directly instead
// of extracting keys into their own files by hand.

import { readFileSync } from "node:fs";
import type { Hex } from "viem";
import { normalizePrivateKey } from "../../agent/src/sepolia.js";

interface DeploymentsShape {
  privateKey?: string;
  auditor?: { privateKey?: string };
  employees?: Array<{ name?: string; address?: string; privateKey?: string }>;
}

/**
 * Loads a private key from `path`. Accepts:
 *   - a raw hex private key (the whole file content)
 *   - `{ "privateKey": "0x..." }`
 *   - `{ "auditor": { "privateKey": "0x..." } }` (a deployments.json)
 *   - `{ "employees": [{ "name"/"address", "privateKey" }, ...] }`, in which
 *     case `selector` (an employee name or address, case-insensitive) picks
 *     which entry to use — required when the file has more than one
 *     employee and no top-level/auditor key to fall back to.
 */
export function loadPrivateKeyFromFile(path: string, selector?: string): Hex {
  const raw = readFileSync(path, "utf8").trim();

  let parsed: DeploymentsShape | undefined;
  try {
    parsed = JSON.parse(raw) as DeploymentsShape;
  } catch {
    // Not JSON — the whole file is treated as a raw key below.
  }

  if (parsed !== undefined) {
    // An explicit selector always means "pick this employee" — checked first
    // so it can't be silently shadowed by an unrelated auditor/top-level key
    // sitting in the same deployments file (both commonly coexist).
    if (selector !== undefined) {
      if (parsed.employees === undefined) {
        throw new Error(`--employee was given but ${path} has no "employees" field.`);
      }
      const needle = selector.toLowerCase();
      const match = parsed.employees.find(
        (e) => e.name?.toLowerCase() === needle || e.address?.toLowerCase() === needle,
      );
      if (match === undefined) {
        throw new Error(`No employee named or addressed "${selector}" found in ${path}.`);
      }
      if (typeof match.privateKey !== "string") {
        throw new Error(`Employee "${selector}" in ${path} has no privateKey field.`);
      }
      return normalizePrivateKey(match.privateKey);
    }

    if (typeof parsed.privateKey === "string") return normalizePrivateKey(parsed.privateKey);
    if (typeof parsed.auditor?.privateKey === "string") return normalizePrivateKey(parsed.auditor.privateKey);

    if (parsed.employees !== undefined) {
      const names = parsed.employees.map((e) => e.name ?? e.address ?? "?").join(", ");
      throw new Error(`${path} has multiple employees (${names}) — pass --employee <name-or-address> to pick one.`);
    }

    throw new Error(`${path} is valid JSON but has none of the expected shapes (privateKey/auditor/employees).`);
  }

  return normalizePrivateKey(raw);
}
